-- ============================================================
-- OFM MARKETPLACE — Supabase Schema
-- Copiá y pegá TODO esto en: Supabase → SQL Editor → New query → Run
-- ============================================================

-- ---------- CATEGORIES ----------
create table if not exists categories (
  id          uuid primary key default gen_random_uuid(),
  user_id     uuid not null references auth.users(id) on delete cascade,
  name        text not null,
  created_at  timestamptz default now()
);

-- ---------- CONTACTS (sellers / buyers / leads) ----------
create table if not exists contacts (
  id          uuid primary key default gen_random_uuid(),
  user_id     uuid not null references auth.users(id) on delete cascade,
  type        text not null check (type in ('seller','buyer','lead')),
  name        text not null,
  telegram    text,
  notes       text,
  looking_for text,
  categories  text,
  created_at  timestamptz default now()
);

-- ---------- MODELS ----------
create table if not exists models (
  id            uuid primary key default gen_random_uuid(),
  user_id       uuid not null references auth.users(id) on delete cascade,
  seq           bigint generated by default as identity,
  name          text not null,
  status        text default 'available' check (status in ('available','reserved','sold')),
  category      text,
  priority      text default 'normal' check (priority in ('normal','hot')),
  seller_id     uuid references contacts(id) on delete set null,
  buyer_id      uuid references contacts(id) on delete set null,
  age           text,
  origin        text,
  phone         text,
  pct           text,
  time_per_day  text,
  english       text,
  content       text,
  contract      text default 'No',
  agency        text default 'No',
  start_when    text,
  social        text default 'No',
  tiktok        text default 'No',
  blocked       text,
  verified      text default 'No',
  fee           text,
  notes         text,
  photos        jsonb default '[]'::jsonb,
  price_listing numeric,
  price_final   numeric,
  commission    numeric,
  market_cut    numeric,
  created_at    timestamptz default now()
);

-- ---------- SEARCHES (búsquedas activas) ----------
create table if not exists searches (
  id           uuid primary key default gen_random_uuid(),
  user_id      uuid not null references auth.users(id) on delete cascade,
  title        text not null,
  buyer_id     uuid references contacts(id) on delete set null,
  requirements text,
  status       text default 'active' check (status in ('active','resolved')),
  created_at   timestamptz default now()
);

-- ---------- ALERTS (manuales) ----------
create table if not exists alerts (
  id          uuid primary key default gen_random_uuid(),
  user_id     uuid not null references auth.users(id) on delete cascade,
  title       text not null,
  model_id    uuid references models(id) on delete set null,
  notes       text,
  due_date    date,
  priority    text default 'normal' check (priority in ('normal','high')),
  done        boolean default false,
  created_at  timestamptz default now()
);

-- ---------- ACTIVITY LOG (historial) ----------
create table if not exists activity_log (
  id          uuid primary key default gen_random_uuid(),
  user_id     uuid not null references auth.users(id) on delete cascade,
  model_id    uuid references models(id) on delete cascade,
  text        text not null,
  type        text default '',
  created_at  timestamptz default now()
);

-- ---------- SETTINGS (config Telegram) ----------
create table if not exists settings (
  user_id          uuid primary key references auth.users(id) on delete cascade,
  telegram_token   text,
  telegram_chat_id text,
  updated_at       timestamptz default now()
);

-- ============================================================
-- ROW LEVEL SECURITY — cada usuario solo ve sus propios datos
-- ============================================================
alter table categories   enable row level security;
alter table contacts     enable row level security;
alter table models       enable row level security;
alter table searches     enable row level security;
alter table alerts       enable row level security;
alter table activity_log enable row level security;
alter table settings     enable row level security;

-- Policies (todas: el dueño de la fila puede todo)
create policy "own_categories"   on categories   for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "own_contacts"     on contacts     for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "own_models"       on models       for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "own_searches"     on searches     for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "own_alerts"       on alerts       for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "own_activity"     on activity_log for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "own_settings"     on settings     for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

-- ============================================================
-- STORAGE — bucket para fotos de modelos
-- ============================================================
insert into storage.buckets (id, name, public)
values ('model-photos', 'model-photos', true)
on conflict (id) do nothing;

-- Política de storage: usuarios autenticados pueden subir/leer/borrar
create policy "auth_upload_photos" on storage.objects
  for insert to authenticated
  with check (bucket_id = 'model-photos');

create policy "auth_read_photos" on storage.objects
  for select to authenticated
  using (bucket_id = 'model-photos');

create policy "public_read_photos" on storage.objects
  for select to anon
  using (bucket_id = 'model-photos');

create policy "auth_delete_photos" on storage.objects
  for delete to authenticated
  using (bucket_id = 'model-photos');

create policy "auth_update_photos" on storage.objects
  for update to authenticated
  using (bucket_id = 'model-photos');

-- ============================================================
-- LISTO. Ahora andá a Authentication → Users → Add user
-- y creá tu usuario (email + password) para poder loguearte.
-- ============================================================
